// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Owin.Compression.Standard")>]
[<assembly: AssemblyProductAttribute("Owin.Compression")>]
[<assembly: AssemblyDescriptionAttribute("Compression (Deflate / GZip) module for Microsoft OWIN Selfhost filesystem pipeline.")>]
[<assembly: AssemblyVersionAttribute("1.0.39")>]
[<assembly: AssemblyFileVersionAttribute("1.0.39")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Owin.Compression.Standard"
    let [<Literal>] AssemblyProduct = "Owin.Compression"
    let [<Literal>] AssemblyDescription = "Compression (Deflate / GZip) module for Microsoft OWIN Selfhost filesystem pipeline."
    let [<Literal>] AssemblyVersion = "1.0.39"
    let [<Literal>] AssemblyFileVersion = "1.0.39"
