// Auto-Generated by build.fsx; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Owin.Compression")>]
[<assembly: AssemblyProductAttribute("Owin.Compression")>]
[<assembly: AssemblyDescriptionAttribute("Compression (Deflate / GZip / Brotli) and eTag caching module for Microsoft OWIN self-host and ASP.NET Core/Kestrel.")>]
[<assembly: AssemblyMetadataAttribute("Authors", "Tuomas Hietanen")>]
[<assembly: AssemblyMetadataAttribute("Description", "Compression (Deflate / GZip / Brotli) module for Microsoft OWIN self-host and ASP.NET Core/Kestrel web servers with built-in eTag caching. With this module you can compress large files (like concatenated *.js or *.css files) to reduce the amount of web traffic.")>]
[<assembly: AssemblyMetadataAttribute("Tags", "OWIN SelfHost GZip Deflate Brotli AspNetCore Kestrel compress pack self host file system pipeline Microsoft")>]
[<assembly: AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/Thorium/Owin.Compression")>]
[<assembly: AssemblyMetadataAttribute("RepositoryRaw", "https://raw.github.com/Thorium")>]
[<assembly: AssemblyVersionAttribute("1.0.51")>]
[<assembly: AssemblyFileVersionAttribute("1.0.51")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Owin.Compression"
    let [<Literal>] AssemblyProduct = "Owin.Compression"
    let [<Literal>] AssemblyDescription = "Compression (Deflate / GZip / Brotli) and eTag caching module for Microsoft OWIN self-host and ASP.NET Core/Kestrel."
    let [<Literal>] AssemblyVersion = "1.0.51"
    let [<Literal>] AssemblyFileVersion = "1.0.51"
